version: "2"
services:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
  app:
    container_name: app
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 3000:3000
      - 80:80
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - WS_HOST=0.0.0.0
      - WS_PORT=3000
      - RNODE_HOST=172.17.0.1
      - RNODE_GRPC_PORT=40401
      - RNODE_HTTP_PORT=40403
    expose:
      - 3000
      - 80
    command: sh -c 'npm i && node index.js'
    depends_on:
      - redis
