version: "2"
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  app:
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
    command: sh -c 'npm i && node index.js'
    expose:
      - 3000
