version: "2"
services:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
  dappy-node:
    container_name: dappy-node
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 3000:3000 # HTTP_PORT
      - 3001:3001 # HTTPS_PORT
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=3000
      - HTTPS_PORT=3001
      - RNODE_HOST=172.17.0.1
      - RNODE_GRPC_PORT=40401
      - RNODE_HTTP_PORT=40403
      - RNODE_DEPLOY_HOST=172.17.0.1
      - RNODE_DEPLOY_GRPC_PORT=40401
      - RNODE_DEPLOY_HTTP_PORT=40403
    expose:
      - 3000
      - 80
    command: sh -c 'npm i && node index.js'
    depends_on:
      - redis
